#!/usr/bin/env python3
from pathlib import Path
import shutil, zipfile
import cairosvg
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Flowable, Image, HRFlowable
from reportlab.lib.units import mm

BASE = Path(__file__).resolve().parents[1]
SKILL = BASE / "skills" / "idjoy-seo"
PDF = SKILL / "resources" / "idjoy-seo-ai-search-checklist.pdf"
LOGO_SVG = SKILL / "assets" / "idjoy-logo.svg"
LOGO_PNG = SKILL / "assets" / "idjoy-logo.png"
ZIP = BASE / "idjoy-seo.zip"
SKILL.joinpath("resources").mkdir(parents=True, exist_ok=True)

cairosvg.svg2png(bytestring=LOGO_SVG.read_bytes(), write_to=str(LOGO_PNG), output_width=512, output_height=512)

NAVY=colors.HexColor("#1B2541"); INK=colors.HexColor("#152033"); MUTED=colors.HexColor("#667085")
PALE=colors.HexColor("#F4F6F8"); WARM=colors.HexColor("#F8F5EF"); LINE=colors.HexColor("#D8DEE8"); WHITE=colors.white
PW,PH=A4; LEFT=17*mm; RIGHT=17*mm; TOP=18*mm; BOTTOM=18*mm
H1=ParagraphStyle("H1",fontName="Helvetica-Bold",fontSize=25,leading=28,textColor=NAVY,spaceAfter=7*mm)
H2=ParagraphStyle("H2",fontName="Helvetica-Bold",fontSize=16,leading=19,textColor=NAVY,spaceBefore=2*mm,spaceAfter=3*mm)
H3=ParagraphStyle("H3",fontName="Helvetica-Bold",fontSize=10.5,leading=13,textColor=INK,spaceAfter=1.5*mm)
BODY=ParagraphStyle("Body",fontName="Helvetica",fontSize=9.3,leading=13,textColor=INK,spaceAfter=2.2*mm)
SMALL=ParagraphStyle("Small",fontName="Helvetica",fontSize=7.8,leading=10.3,textColor=MUTED)
TINY=ParagraphStyle("Tiny",fontName="Helvetica",fontSize=6.8,leading=8.5,textColor=MUTED)
WHITE_BODY=ParagraphStyle("WhiteBody",fontName="Helvetica",fontSize=10.5,leading=15,textColor=WHITE)
EYEBROW=ParagraphStyle("Eyebrow",fontName="Helvetica-Bold",fontSize=7.5,leading=9,textColor=NAVY,spaceAfter=3*mm)

class Checkbox(Flowable):
    def __init__(self,size=3.4*mm): super().__init__(); self.size=size; self.width=size; self.height=size
    def draw(self): self.canv.setStrokeColor(NAVY); self.canv.setLineWidth(.8); self.canv.rect(0,0,self.size,self.size,stroke=1,fill=0)
class ScoreBox(Flowable):
    def __init__(self,label,width=38*mm,height=20*mm): super().__init__(); self.label=label; self.width=width; self.height=height
    def draw(self):
        c=self.canv; c.setStrokeColor(LINE); c.setFillColor(PALE); c.roundRect(0,0,self.width,self.height,3*mm,stroke=1,fill=1)
        c.setFillColor(MUTED); c.setFont("Helvetica-Bold",7); c.drawString(3*mm,self.height-5*mm,self.label.upper())
        c.setFillColor(NAVY); c.setFont("Helvetica-Bold",15); c.drawString(3*mm,5*mm,"____ / 10")

def footer(c,doc):
    if doc.page==1: return
    c.saveState(); c.setStrokeColor(LINE); c.line(LEFT,12*mm,PW-RIGHT,12*mm); c.setFillColor(MUTED); c.setFont("Helvetica",6.8)
    c.drawString(LEFT,7.7*mm,"IDJOY (Pty) Ltd | Evidence-led websites & search visibility | idjoy.co.za | Reg. 2024/464477/07")
    c.drawRightString(PW-RIGHT,7.7*mm,str(doc.page)); c.restoreState()

def intro(num,title,why): return [Paragraph(f"{num:02d} / COMPANY CHECKLIST",EYEBROW),Paragraph(title,H1),Paragraph(why,BODY),Spacer(1,2*mm)]
def checklist(items):
    rows=[]
    for a,b in items:
        rows.append([Checkbox(),Paragraph(f'<b>{a}</b><br/><font color="#667085" size="7.2">{b}</font>',SMALL),Paragraph("Owner: __________<br/>Due: __________",TINY)])
    t=Table(rows,colWidths=[7*mm,132*mm,31*mm],hAlign="LEFT")
    t.setStyle(TableStyle([("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),0),("RIGHTPADDING",(0,0),(-1,-1),1.5*mm),("TOPPADDING",(0,0),(-1,-1),2.4*mm),("BOTTOMPADDING",(0,0),(-1,-1),2.4*mm),("LINEBELOW",(0,0),(-1,-2),.35,LINE)])); return t
def note(title,body,fill=PALE):
    t=Table([[Paragraph(title,H3),Paragraph(body,SMALL)]],colWidths=[42*mm,126*mm]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),fill),("BOX",(0,0),(-1,-1),.6,LINE),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),4*mm),("RIGHTPADDING",(0,0),(-1,-1),4*mm),("TOPPADDING",(0,0),(-1,-1),3.5*mm),("BOTTOMPADDING",(0,0),(-1,-1),3.5*mm)])); return t
def scores(labels): return Table([[ScoreBox(x) for x in labels]],colWidths=[42*mm]*len(labels),hAlign="LEFT",style=[("LEFTPADDING",(0,0),(-1,-1),0),("RIGHTPADDING",(0,0),(-1,-1),4*mm)])

sections=[
(1,"Business clarity and measurement","SEO becomes expensive when the company has not defined the buyer, commercial offer and result worth measuring.",[
("Write the primary commercial outcome for the website in one sentence.","Qualified enquiries, bookings, quote requests or sales."),("Name the 1-3 buyer groups the website must help.","Use real roles, industries, problems or locations - not everyone."),("List the services/products that directly generate revenue.","Separate core offers from support information and experiments."),("Define what a qualified enquiry looks like.","Include fit, budget, location, urgency or service type where relevant."),("Confirm analytics is collecting useful events.","Track forms, calls, WhatsApp, bookings, checkout or other commercial actions."),("Connect Google Search Console and Bing Webmaster Tools.","Use first-party evidence for indexation, queries and performance."),("Record a baseline before major changes.","Capture qualified enquiries, impressions, clicks and key organic landing pages."),("Assign one person who owns search measurement.","A report with no decision owner is only documentation.")],["Clarity","Measurement","Ownership"]),
(2,"Crawling, indexing and technical access","A brilliant page cannot perform if search systems cannot reliably reach, render or index the version you intend.",[
("Verify important public pages return a successful HTTP response.","Fix broken, looping, protected or server-error pages."),("Review robots.txt for accidental blocks.","Money pages should not be blocked by mistake."),("Confirm XML sitemaps include canonical, indexable pages only.","Remove redirecting, duplicate, noindex and private URLs."),("Check canonical tags on important templates.","Do not point distinct pages to the wrong canonical."),("Check noindex directives on key pages.","A staging rule copied to production can erase visibility."),("Confirm HTTPS, one preferred hostname and clean redirects.","Resolve URL variants consistently."),("Test JavaScript-rendered content.","Important text and links should not depend on fragile interactions."),("Inspect status codes after redesigns or migrations.","Use 301 redirects for replaced URLs."),("Keep private customer/account routes out of search.","robots.txt is not access control.")],["Access","Indexing","Migration safety"]),
(3,"Website structure and search intent","The site should mirror the way a buyer understands the problem - not an internal org chart.",[
("Give every important service a useful canonical destination.","Avoid one vague Services page if buyers search for distinct offers."),("Map one primary intent to each important page.","Prevent thin pages from competing for the same job."),("Use descriptive navigation labels.","Use labels buyers understand without decoding."),("Keep high-value pages within sensible click depth.","Important pages should be reachable through normal navigation."),("Create useful topic hubs only where a topic has depth.","Hubs should explain and connect, not hold keywords."),("Avoid doorway pages for every city or keyword variant.","Location pages need real local usefulness and evidence."),("Use breadcrumbs where hierarchy is meaningful.","Help users and systems understand location in the site."),("Maintain a URL inventory during major changes.","Know what is kept, merged, redirected or retired.")],["Architecture","Intent","Navigation"]),
(4,"On-page clarity and useful content","Answer the buyer's question quickly, then earn the next minute of attention with useful depth.",[
("Make the page title specific, useful and unique.","Lead with topic and value; avoid keyword stuffing."),("Use one clear H1 that describes the page.","Match the user's expected destination."),("Answer the primary question near the top.","Do not hide the offer behind brand poetry."),("Explain who the service is for and when it is relevant.","Specificity improves qualification."),("Explain outcomes before drowning the visitor in features.","Translate expertise into the buyer's desired result."),("Break complex work into understandable stages.","A visible process reduces uncertainty."),("Write descriptive link text.","Give context instead of generic click here links."),("Use original images, diagrams, examples or data.","Commodity text alone is rarely defensible."),("Add a next step matched to readiness.","Inspect, calculate, download, book, enquire or request quote.")],["Relevance","Usefulness","Conversion"]),
(5,"Trust, evidence and structured data","A strong public story is specific, consistent and supported by evidence a buyer can inspect.",[
("Show the real business name and contact route clearly.","Keep it consistent across important profiles."),("Show who is behind the business.","Use real people and relevant credentials."),("Publish case studies with specific problems, work and proof.","Do not invent conversion figures."),("Use testimonials/reviews only when authentic.","Never manufacture reviews."),("Show certifications, memberships or compliance proof.","Explain what the credential proves."),("Make policies easy to find.","Privacy, terms and service conditions reduce uncertainty."),("Implement structured data only for facts present on the page.","Schema describes; it does not invent."),("Validate structured data after deployment.","Check syntax and rendered output."),("Keep organisation details consistent.","Name, URL, phone, address and profiles should not contradict.")],["Evidence","Entity clarity","Schema"]),
(6,"Local SEO for companies serving real locations","Local visibility comes from accurate business information, relevant location evidence and a site that explains where the company can help.",[
("Claim and maintain Google Business Profile where eligible.","Use real name, primary category, hours and contact information."),("Keep name, address/service area and phone details consistent.","Fix meaningful contradictions."),("Choose categories based on actual services.","Do not add unrelated categories for search volume."),("Complete services, products, photos and business description.","Use current information and real media."),("Build an ethical review process.","Never buy, gate or fabricate reviews."),("Create location pages only with genuine relevance.","Add local proof, projects, logistics or constraints."),("Embed local evidence in case studies.","Show area, sector, challenge and delivery context where useful."),("Track local enquiries, not rankings alone.","Calls, directions, messages and qualified leads matter more.")],["Profile","Consistency","Local evidence"]),
(7,"Page experience, mobile and performance","Performance is part of the buying experience. Optimise the pages people actually use instead of chasing a lab score.",[
("Test the site on a real mobile viewport.","Check navigation, forms, sticky elements, tap targets and overflow."),("Monitor Core Web Vitals on important templates.","Prioritise recurring real-user issues."),("Compress and size images appropriately.","Avoid oversized hero assets."),("Reduce render-blocking or unnecessary scripts.","Third-party tags can quietly erode experience."),("Prevent major layout shifts.","Reserve space for media, fonts and dynamic elements."),("Make forms short, clear and resilient.","Label fields and show errors well."),("Check keyboard and basic accessibility.","Semantics, contrast, focus and labels improve robustness."),("Measure performance after deployment.","A redesign can regress in production.")],["Mobile","Performance","Accessibility"]),
(8,"AI-search readiness","Treat AI-assisted discovery as an extension of good SEO: make public facts clear, crawlable, consistent and worth citing.",[
("Keep important business facts on public, crawlable pages.","Do not leave services, locations, people or proof only in images/private PDFs."),("Do not block search crawlers you intentionally want.","Review robots rules, CDN/WAF rules and bot mitigation together."),("For ChatGPT search, review access for OAI-SearchBot.","GPTBot is a separate training-related control."),("Do not create AI-only claims, fake citations or hidden machine text.","Public evidence should help humans too."),("Use schema to describe real entities and content.","There is no special guaranteed AI-ranking schema."),("Keep concise factual summaries near their evidence.","Reduce ambiguity without answer spam."),("Build quotable original evidence.","Case studies, data, methods and calculators can add value."),("Treat llms.txt as optional experimentation.","Do not present it as a ranking requirement."),("Measure AI visibility with repeated tests and referral/conversion data.","One chatbot screenshot is not market share.")],["Crawler access","Evidence","Measurement"]),
(9,"Content portfolio and internal linking","Publish less generic content and more pages that answer a commercial question, show evidence, or support a decision.",[
("Inventory existing content before creating more.","Keep, refresh, consolidate, redirect or retire."),("Prioritise topics close to buyer decisions.","Cost, fit, comparison, process, risk, alternatives and requirements."),("Create topic clusters only where expertise and demand justify them.","Avoid thin variants for coverage theatre."),("Link informational content to the relevant commercial destination.","Make the next step useful."),("Link commercial pages back to evidence.","Case studies, FAQs and credentials help validation."),("Refresh stale facts, screenshots and service details.","An indexed page can still lose trust when outdated."),("Merge pages duplicating the same intent.","Consolidation can improve clarity and maintenance."),("Keep editorial standards for AI-assisted writing.","Human review must verify claims, originality, examples and voice.")],["Portfolio","Internal links","Editorial quality"]),
(10,"Measurement, maintenance and the next 90 days","Search is a system, not a one-time launch task. Build a rhythm that connects visibility changes to business outcomes.",[
("Review Search Console and Bing data monthly.","Watch indexation, query groups, landing pages and unusual changes."),("Review qualified organic enquiries monthly.","Separate traffic growth from commercial progress."),("Track major website changes on a changelog.","Know what changed and when."),("Re-check crawl/index rules after deployments.","Robots, canonicals, sitemaps and redirects deserve regression tests."),("Review content performance by intent, not word count.","Ask whether each page helps discovery, trust, evaluation or conversion."),("Re-test AI-search visibility using a stable prompt set.","Record engine, date, result, cited sources and material accuracy."),("Review external business profiles quarterly.","Update hours, services, staff, locations and key facts."),("Build the next quarter around the biggest evidence-backed constraint.","Do not let a content calendar substitute for strategy.")],["Business impact","Search evidence","Maintenance"])
]

story=[Spacer(1,18*mm),Image(str(LOGO_PNG),width=22*mm,height=22*mm),Spacer(1,7*mm),Paragraph("IDJOY / PRACTICAL COMPANY RESOURCE",EYEBROW),Paragraph("SEO + AI Search<br/>Readiness Checklist",H1),Paragraph("Make your company easier to <b>understand, trust and find</b> - in Google, Bing, AI-assisted search and the buying journey that happens after discovery.",BODY),Spacer(1,6*mm)]
card=Table([[Paragraph("A practical, evidence-led checklist for business owners and marketing teams. No ranking guarantees. No mystery scores. No AI-search hacks that distract from the fundamentals.",WHITE_BODY)]],colWidths=[167*mm]); card.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),NAVY),("LEFTPADDING",(0,0),(-1,-1),8*mm),("RIGHTPADDING",(0,0),(-1,-1),8*mm),("TOPPADDING",(0,0),(-1,-1),8*mm),("BOTTOMPADDING",(0,0),(-1,-1),8*mm)]))
story += [card,Spacer(1,16*mm),Paragraph("<b>Use it before:</b> a website redesign, an SEO retainer, a content campaign, an AI-search visibility project, or any major website investment.",BODY),Spacer(1,8*mm),note("COMPANY DETAILS",'<b>IDJOY (Pty) Ltd</b><br/>Pretoria, South Africa<br/>Registration: 2024/464477/07<br/>Website: <link href="https://idjoy.co.za" color="#1B2541">idjoy.co.za</link><br/>Evidence-led websites, SEO and search visibility.',WARM),Spacer(1,15*mm),Paragraph("Prepared by IDJOY | Version 1.0 | August 2026",SMALL),PageBreak()]
story += intro(0,"How to use this checklist","Score the company honestly, fix blockers first, then build the content and evidence system that compounds over time.")
story += [note("THE THREE TESTS","<b>Understand:</b> Can a buyer and a search system tell what you do, who it is for and where you operate?<br/><br/><b>Trust:</b> Can they inspect proof, credentials, people, policies, reviews, case studies and specific claims?<br/><br/><b>Find:</b> Can crawlers reach the right pages, interpret them and connect them to the searches and questions buyers use?"),Spacer(1,5*mm),Paragraph("Score each section from 0 to 10",H2),checklist([("0-3: Unclear or unverified","Important pieces are missing, blocked or assumptions."),("4-6: Working but inconsistent","Foundations exist, but gaps make discovery or buying harder."),("7-8: Strong","Important journeys are clear, evidence-led and measurable."),("9-10: Mature","The system is maintained, measured and improved without hacks.")]),Spacer(1,5*mm),note("PRIORITY RULE","<b>P0</b> - blocks crawling, indexing, trust or enquiries. Fix now.<br/><b>P1</b> - material visibility or conversion issue. Fix next.<br/><b>P2</b> - meaningful improvement. Schedule.<br/><b>P3</b> - polish or experiment after the system works.",WARM),PageBreak()]
for n,t,w,items,sc in sections: story += intro(n,t,w)+[checklist(items),Spacer(1,5*mm),scores(sc),PageBreak()]

story += intro(11,"Turn the audit into a 30 / 60 / 90 day plan","A checklist only creates value when it changes priorities. Convert findings into a short operating plan.")
plan=[[Paragraph("<b>30 DAYS - REMOVE BLOCKERS</b>",H3),Paragraph("<b>60 DAYS - BUILD EVIDENCE</b>",H3),Paragraph("<b>90 DAYS - COMPOUND</b>",H3)],[Paragraph("P0/P1 crawl and index fixes<br/>Measurement baseline<br/>Primary page clarity<br/>Business info consistency<br/>Critical mobile/form issues<br/><br/>Owner: __________",SMALL),Paragraph("Service-page clarity<br/>Case studies and proof<br/>Internal-link routes<br/>Local profile improvements<br/>Schema on verified entities<br/><br/>Owner: __________",SMALL),Paragraph("High-intent content<br/>Refresh/merge weak pages<br/>Performance improvements<br/>AI-search monitoring set<br/>Quarterly roadmap<br/><br/>Owner: __________",SMALL)]]
pt=Table(plan,colWidths=[56*mm]*3); pt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),NAVY),("TEXTCOLOR",(0,0),(-1,0),WHITE),("BOX",(0,0),(-1,-1),.6,LINE),("INNERGRID",(0,0),(-1,-1),.35,LINE),("VALIGN",(0,0),(-1,-1),"TOP"),("LEFTPADDING",(0,0),(-1,-1),4*mm),("RIGHTPADDING",(0,0),(-1,-1),4*mm),("TOPPADDING",(0,0),(-1,-1),4*mm),("BOTTOMPADDING",(0,0),(-1,-1),5*mm)])); story += [pt,Spacer(1,7*mm),Paragraph("Leadership scorecard",H2)]
rows=[["Section","Score /10","Top constraint","Next decision"]]+[[f"{n:02d} {t[:28]}","____","________________","________________"] for n,t,_,_,_ in sections]
st=Table(rows,colWidths=[62*mm,20*mm,43*mm,43*mm],repeatRows=1); st.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),PALE),("TEXTCOLOR",(0,0),(-1,0),NAVY),("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),("FONTSIZE",(0,0),(-1,-1),7.2),("GRID",(0,0),(-1,-1),.35,LINE),("LEFTPADDING",(0,0),(-1,-1),2.5*mm),("RIGHTPADDING",(0,0),(-1,-1),2.5*mm),("TOPPADDING",(0,0),(-1,-1),2.1*mm),("BOTTOMPADDING",(0,0),(-1,-1),2.1*mm)])); story += [st,PageBreak()]

story += intro(12,'What "good" looks like',"You need a website that communicates the right facts, earns confidence, is technically accessible and gives measurement enough time to show what is changing.")
story += [note("UNDERSTAND","A qualified buyer can explain what you do, who it is for, why it matters and what happens next after scanning the page for less than a minute."),Spacer(1,3*mm),note("TRUST","Important claims have inspectable proof: real people, credentials, projects, policies, reviews, examples, processes or data."),Spacer(1,3*mm),note("FIND","Important pages can be crawled, indexed and connected to the language buyers use. Search and AI systems encounter clear, consistent public information."),Spacer(1,7*mm),Paragraph("Before you pay for more traffic",H2),Paragraph("Fix clarity and evidence gaps that make qualified visitors hesitate. More traffic sent into an unclear buying journey usually scales the confusion too.",BODY),Spacer(1,5*mm),note("FREE NEXT STEP",'Use the IDJOY AI Visibility Scanner to inspect public crawler access, machine understanding, business clarity, trust evidence and search footprint. Visit <link href="https://idjoy.co.za" color="#1B2541"><b>idjoy.co.za</b></link>.',WARM),Spacer(1,7*mm),Paragraph("Reference standard",H2),Paragraph("Built around durable guidance from Google Search Central, Bing Webmaster guidance, OpenAI crawler documentation and the open Agent Skills ecosystem. Re-check current platform documentation before crawler-specific changes.",SMALL),Spacer(1,8*mm),HRFlowable(width="100%",thickness=.6,color=LINE),Spacer(1,5*mm),Paragraph("<b>IDJOY (Pty) Ltd</b>",H2),Paragraph("Evidence-led websites, SEO and search visibility for businesses that need buyers to understand complex work, inspect the proof and know what to do next.",BODY),Paragraph("Pretoria, South Africa | Registration 2024/464477/07 | idjoy.co.za",SMALL),Spacer(1,4*mm),Paragraph("<b>Important:</b> SEO rankings, search features and AI citations are not guaranteed. Use this as an operating checklist, not a promise of placement or revenue.",TINY)]

doc=SimpleDocTemplate(str(PDF),pagesize=A4,rightMargin=RIGHT,leftMargin=LEFT,topMargin=TOP,bottomMargin=BOTTOM,title="IDJOY SEO + AI Search Readiness Checklist",author="IDJOY (Pty) Ltd",subject="Practical company SEO and AI-search readiness checklist")
doc.build(story,onFirstPage=footer,onLaterPages=footer)

with zipfile.ZipFile(ZIP,"w",zipfile.ZIP_DEFLATED) as z:
    for f in SKILL.rglob("*"):
        if f.is_file(): z.write(f,Path("idjoy-seo")/f.relative_to(SKILL))
print(f"Built {PDF} and {ZIP}")
